services:
  - type: web
    name: taste-town-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    runtime: python
    repo: https://github.com/BROM-town-square/brom-e-commerce-backend
    branch: row
    autoDeploy: true

    envVars:
      - key: DATABASE_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
